### ISSUE TITLE
Maya 2025: pyside2 is not compatible

### ISSUE THREAD

**Issue by adrienparis** [YannGenty/yg_weightTool#2]
Hello dear Yann,

I would like to inform you that PySide2 is no longer supported in Maya 2025.

To ensure compatibility, I recommend adding the following lines to your code:
```py
try:
    from PySide2.QtGui import QCursor
except:
    from PySide6.QtGui import QCursor
```

This adjustment will allow your code to work seamlessly with both PySide2 and PySide6.

Best regards,

**Comment by YannGenty** [comment]
Hi Adrien,

Thanks a lot for the feedback, I'll change it as soon as possible.

cya !
